In [2]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(5.1223e-09, grad_fn=<MeanBackward0>)

In [4]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

dense = MyLinear(5, 3)
dense.weight

Parameter containing:
tensor([[-2.9634e+00,  9.8747e-01, -4.7015e-01],
        [-9.5121e-01, -1.9981e-01, -7.6261e-01],
        [-2.1715e+00,  1.5005e+00, -4.1665e-01],
        [ 8.1096e-02,  2.2969e-03,  1.3339e+00],
        [ 2.7455e-03,  2.2182e+00, -8.5993e-01]], requires_grad=True)

In [10]:
dense(torch.rand(2, 5))

tensor([[0.9564, 1.6620, 0.0000],
        [0.0000, 2.9200, 0.0000]])

In [11]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[28.0756],
        [17.9536]])