In [2]:
import torch
from torch import nn
from torch.nn import functional as F

x_file = './data/x-file'

x = torch.arange(4)
torch.save(x, x_file)

x2 = torch.load(x_file)
x2

tensor([0, 1, 2, 3])

In [3]:
x_files = './data/x-files'

y = torch.zeros(4)
torch.save([x, y], x_files)
x2, y2 = torch.load(x_files)
x2, y2

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [4]:
my_dict = './data/mydict'

mydict = {'x': x, 'y': y}
torch.save(mydict, my_dict)
mydict2 = torch.load(my_dict)
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [5]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)
    
    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)
Y

tensor([[-0.1781, -0.0882, -0.2707, -0.0355, -0.1218,  0.0219,  0.2451, -0.1253,
          0.0063,  0.0509],
        [ 0.1732, -0.1594,  0.3282, -0.0630,  0.0529, -0.1457,  0.4526, -0.1010,
         -0.0865, -0.0253]], grad_fn=<AddmmBackward0>)

In [6]:
mlp_params = './data/mlp.params'

torch.save(net.state_dict(), mlp_params)

In [7]:
clone = MLP()
clone.load_state_dict(torch.load(mlp_params))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [8]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])